services:
  - type: web
    name: Leetcodeurl-s
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production

