import React, { useRef } from 'react';
import { Download, QrCode, ShieldCheck, Share2 } from 'lucide-react';

interface IDCardGeneratorProps {
  studentName: string;
  regNo: string;
  deptName: string;
  yearLevel: string;
  totalSolved: number;
  collegeRank?: number;
  streakCount?: number;
}

export const IDCardGenerator: React.FC<IDCardGeneratorProps> = ({
  studentName,
  regNo,
  deptName,
  yearLevel,
  totalSolved,
  collegeRank = 1,
  streakCount = 0
}) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  const generateAndDownloadPass = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Dimensions
    canvas.width = 600;
    canvas.height = 360;

    // Background Gradient (Dark Navy / Emerald Vault)
    const grad = ctx.createLinearGradient(0, 0, 600, 360);
    grad.addColorStop(0, '#0F172A');
    grad.addColorStop(1, '#022C22');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, 600, 360);

    // Border
    ctx.strokeStyle = '#10B981';
    ctx.lineWidth = 4;
    ctx.strokeRect(10, 10, 580, 340);

    // College Header
    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'bold 16px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('NANDHA ENGINEERING COLLEGE, ERODE', 300, 45);

    ctx.fillStyle = '#10B981';
    ctx.font = 'bold 11px sans-serif';
    ctx.fillText('OFFICIAL LEETCODE PLATFORM STUDENT PASS', 300, 65);

    // Divider Line
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(30, 80);
    ctx.lineTo(570, 80);
    ctx.stroke();

    // Student Info (Left Column)
    ctx.textAlign = 'left';
    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 11px sans-serif';
    ctx.fillText('STUDENT NAME', 40, 115);

    ctx.fillStyle = '#FFFFFF';
    ctx.font = 'extrabold 18px sans-serif';
    ctx.fillText(studentName.toUpperCase(), 40, 140);

    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 11px sans-serif';
    ctx.fillText('REGISTER NO', 40, 175);

    ctx.fillStyle = '#10B981';
    ctx.font = 'bold 16px monospace';
    ctx.fillText(regNo, 40, 198);

    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 11px sans-serif';
    ctx.fillText('DEPARTMENT & YEAR', 40, 235);

    ctx.fillStyle = '#CBD5E1';
    ctx.font = 'semibold 13px sans-serif';
    ctx.fillText(`${deptName} • ${yearLevel} Year`, 40, 255);

    // Stats Grid (Right Box)
    ctx.fillStyle = 'rgba(15, 23, 42, 0.7)';
    ctx.fillRect(360, 100, 200, 210);
    ctx.strokeStyle = '#10B981';
    ctx.lineWidth = 1;
    ctx.strokeRect(360, 100, 200, 210);

    ctx.textAlign = 'center';
    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 10px sans-serif';
    ctx.fillText('COLLEGE RANK', 460, 125);

    ctx.fillStyle = '#F59E0B';
    ctx.font = 'bold 24px sans-serif';
    ctx.fillText(`#${collegeRank}`, 460, 155);

    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 10px sans-serif';
    ctx.fillText('PROBLEMS SOLVED', 460, 190);

    ctx.fillStyle = '#10B981';
    ctx.font = 'bold 22px sans-serif';
    ctx.fillText(`${totalSolved}`, 460, 220);

    ctx.fillStyle = '#94A3B8';
    ctx.font = 'bold 10px sans-serif';
    ctx.fillText('ACTIVE STREAK', 460, 250);

    ctx.fillStyle = '#EF4444';
    ctx.font = 'bold 18px sans-serif';
    ctx.fillText(`🔥 ${streakCount} Days`, 460, 275);

    // Footer Verified Stamp
    ctx.textAlign = 'left';
    ctx.fillStyle = '#64748B';
    ctx.font = '10px sans-serif';
    ctx.fillText('VERIFIED AUTOGENERATED DIGITAL PASS • IEEE SMC', 40, 320);

    // Download PNG
    const link = document.createElement('a');
    link.download = `Student_Pass_${regNo}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  return (
    <div className="glass-card p-6 rounded-3xl border border-gray-200 dark:border-gray-800 shadow-xl space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-extrabold text-sm text-gray-900 dark:text-white uppercase tracking-wider flex items-center space-x-2">
            <Share2 className="w-4 h-4 text-emerald-500" />
            <span>Digital Student Pass</span>
          </h3>
          <p className="text-[11px] text-gray-500">Auto-Generated Shareable Digital Badge for LinkedIn / Portfolio</p>
        </div>
        <button
          onClick={generateAndDownloadPass}
          className="flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white rounded-xl text-xs font-bold shadow-md shadow-emerald-600/30 transition-all hover:scale-105"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Download Pass (.PNG)</span>
        </button>
      </div>

      {/* Hidden Canvas for High-Res PNG Export */}
      <canvas ref={canvasRef} className="hidden" />

      {/* Card Preview Box */}
      <div className="p-5 rounded-2xl bg-gradient-to-br from-navy-950 to-emerald-950 text-white border border-emerald-500/30 shadow-2xl relative overflow-hidden">
        <div className="flex items-center justify-between text-xs border-b border-white/10 pb-3">
          <span className="font-extrabold tracking-wider text-emerald-400">NANDHA ENGINEERING COLLEGE</span>
          <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 font-mono text-[10px]">VERIFIED PASS</span>
        </div>

        <div className="py-4 flex items-center justify-between">
          <div className="space-y-1">
            <p className="text-[10px] text-gray-400 font-bold uppercase">Student Name</p>
            <p className="font-extrabold text-base text-white">{studentName}</p>
            <p className="text-[11px] text-emerald-400 font-mono font-bold mt-1">{regNo}</p>
            <p className="text-[10px] text-gray-300">{deptName} • {yearLevel} Year</p>
          </div>

          <div className="text-right space-y-1 bg-navy-900/80 p-3 rounded-xl border border-emerald-500/30">
            <p className="text-[10px] text-gray-400">College Rank</p>
            <p className="text-lg font-extrabold text-amber-400">#{collegeRank}</p>
            <p className="text-[10px] text-emerald-400 font-bold">{totalSolved} Solved</p>
          </div>
        </div>
      </div>
    </div>
  );
};
