"""
Master Institutional Weekly Excel Workbook Generator
Builds exactly TWO department sheets (CSE - Cyber Security, CSE - IoT).
Consumes ONLY the canonical dataset generated by weekly_report_service.
Does NOT query the database.
"""
import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from typing import Dict, Any

from backend.config.report_config import BATCH_CONFIG, get_coordinator_for_department


def build_weekly_performance_excel(data: Dict[str, Any], filepath: str) -> str:
    """
    Generates the simplified 2-sheet submission-ready Excel workbook.
    """
    wb = openpyxl.Workbook()
    wb.active

    report_date = data.get("report_date", "04-09-2026")
    
    # Palette: Professional Institutional Restrained Navy/Slate
    navy_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    brand_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
    sub_header_fill = PatternFill(start_color="E2E8F0", end_color="E2E8F0", fill_type="solid")
    section_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")

    font_title = Font(name="Times New Roman", size=13, bold=True, color="FFFFFF")
    font_subtitle = Font(name="Times New Roman", size=10, italic=True, color="FFFFFF")
    font_tbl_head = Font(name="Times New Roman", size=10, bold=True, color="0F172A")
    font_bold = Font(name="Times New Roman", size=10, bold=True)
    font_regular = Font(name="Times New Roman", size=10)

    thin_border_side = Side(style='thin', color='94A3B8')
    grid_border = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)
    thick_border_side = Side(style='medium', color='1E3A8A')
    outer_border = Border(left=thick_border_side, right=thick_border_side, top=thick_border_side, bottom=thick_border_side)

    align_center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    align_left = Alignment(horizontal='left', vertical='center', wrap_text=True)

    def setup_page_layout(ws):
        ws.page_setup.orientation = ws.ORIENTATION_LANDSCAPE
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToPage = True
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 0

    dept_summaries = data.get("department_summaries", [])
    
    # We strictly enforce only two departments as per Absolute Rule 4.
    allowed_depts = [
        {"code": "CSE(CS)", "sheet_name": "CSE — Cyber Security", "full_name": "Department of Computer Science and Engineering (Cyber Security)"},
        {"code": "CSE(IOT)", "sheet_name": "CSE — IoT", "full_name": "Department of Computer Science and Engineering (IoT)"}
    ]

    for dept_spec in allowed_depts:
        ws = wb.create_sheet(title=dept_spec["sheet_name"])
        setup_page_layout(ws)
        
        # Find department data
        dept_data = next((d for d in dept_summaries if d.get("department") == dept_spec["code"] or d.get("department") == dept_spec["code"].replace("IOT", "IoT")), None)
        if not dept_data:
            dept_data = {"batches": {}} # Fallback to empty if missing
            
        coord = get_coordinator_for_department(dept_spec["code"])
        
        # Header Rows
        ws.merge_cells('A1:M1')
        c1 = ws['A1']
        c1.value = "NANDHA ENGINEERING COLLEGE, ERODE - 638 052\n(An Autonomous Institution, Affiliated to Anna University, Chennai)"
        c1.font = font_title
        c1.fill = navy_fill
        c1.alignment = align_center
        ws.row_dimensions[1].height = 40
        
        ws.merge_cells('A2:M2')
        c2 = ws['A2']
        c2.value = f"{dept_spec['full_name']}"
        c2.font = font_title
        c2.fill = brand_fill
        c2.alignment = align_center
        ws.row_dimensions[2].height = 25
        
        ws.merge_cells('A3:M3')
        c3 = ws['A3']
        c3.value = f"LeetCode Performance — Weekly Report | Date: {report_date} | Academic Coordinator: {coord}"
        c3.font = font_subtitle
        c3.fill = navy_fill
        c3.alignment = align_center
        ws.row_dimensions[3].height = 20

        # Table Header
        headers = [
            ("A4", "A5", "Batch"),
            ("B4", "B5", "No. of Students\n(Total Count)"),
            ("C4", "G4", "Number of Problems Solved"),
            ("H4", "K4", "Weekly Contest Attended"),
            ("L4", "M4", "LeetCode Contest")
        ]
        
        for start, end, val in headers:
            ws.merge_cells(f"{start}:{end}")
            cell = ws[start]
            cell.value = val
            cell.font = font_tbl_head
            cell.fill = sub_header_fill
            cell.alignment = align_center
            cell.border = outer_border
            
        sub_headers = [
            ("C5", "Above 500"), ("D5", "250 - 500"), ("E5", "100 - 249"), ("F5", "1 - 99"), ("G5", "0"),
            ("H5", "4Q"), ("I5", "3Q"), ("J5", "2Q"), ("K5", "1Q"),
            ("L5", "Rating > 1500"), ("M5", "Ranking < 20000")
        ]
        
        for pos, val in sub_headers:
            cell = ws[pos]
            cell.value = val
            cell.font = font_tbl_head
            cell.fill = section_fill
            cell.alignment = align_center
            cell.border = grid_border
            
        ws.row_dimensions[4].height = 25
        ws.row_dimensions[5].height = 30
        
        # Data Rows
        # Batches required: 2025-2029, 2024-2028, 2023-2027 (NO 2026-2030)
        required_batches = [b for b in BATCH_CONFIG if b["key"] != "2026_2030"]
        
        current_row = 6
        for b in required_batches:
            batch_key = b["key"]
            batch_label = b["label"]
            
            b_data = dept_data.get("batches", {}).get(batch_key, {})
            # Ensure safe fallback if metrics are missing
            last_w = b_data.get("last_week", {})
            curr_w = b_data.get("current_week", {})
            
            rows_to_add = [
                (f"{batch_label} — Last Week", last_w),
                (f"{batch_label} — Current Week", curr_w)
            ]
            
            for row_label, row_metrics in rows_to_add:
                ws.row_dimensions[current_row].height = 20
                
                # Fetch explicit values without generating fakes
                tot_students = row_metrics.get("total_students", 0)
                ab_500 = row_metrics.get("prob_above_500", 0)
                p250 = row_metrics.get("prob_250_500", 0)
                p100 = row_metrics.get("prob_100_249", 0)
                p1 = row_metrics.get("prob_1_99", 0)
                p0 = row_metrics.get("prob_0", 0)
                
                q4 = row_metrics.get("q4", 0)
                q3 = row_metrics.get("q3", 0)
                q2 = row_metrics.get("q2", 0)
                q1 = row_metrics.get("q1", 0)
                
                rating = row_metrics.get("rating_above_1500", 0)
                ranking = row_metrics.get("rank_below_20000", 0)
                
                vals = [row_label, tot_students, ab_500, p250, p100, p1, p0, q4, q3, q2, q1, rating, ranking]
                
                for c_idx, val in enumerate(vals, start=1):
                    cell = ws.cell(row=current_row, column=c_idx, value=val)
                    cell.font = font_bold if c_idx <= 2 else font_regular
                    cell.alignment = align_left if c_idx == 1 else align_center
                    cell.border = grid_border
                    
                current_row += 1

        # Column widths
        widths = {'A': 30, 'B': 18, 'C': 12, 'D': 12, 'E': 12, 'F': 12, 'G': 12, 'H': 10, 'I': 10, 'J': 10, 'K': 10, 'L': 15, 'M': 15}
        for col, width in widths.items():
            ws.column_dimensions[col].width = width

    # Cleanup default sheet
    if "Sheet" in wb.sheetnames:
        wb.remove(wb["Sheet"])
        
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    wb.save(filepath)
    return filepath
