"""
Master Institutional Weekly Excel Workbook Generator
Builds official simplified 7-sheet LeetCode weekly performance report workbook.
Consumes ONLY the canonical dataset generated by weekly_report_service.
Does NOT query the database.

Sheets:
  01_CSE_CS_Matrix
  02_CSE_IOT_Matrix
  03_II_Year
  04_III_Year
  05_IV_Year
  06_Overall_Summary
  07_Not_Attended
  (08_Report_Errors — ONLY if actual errors exist)
"""
import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from typing import Dict, Any, List, Optional

from backend.config.report_config import BATCH_CONFIG, get_coordinator_for_department


def build_weekly_performance_excel(data: Dict[str, Any], filepath: str) -> str:
    """
    Generates the simplified 7-sheet submission-ready Excel workbook.
    """
    wb = openpyxl.Workbook()
    default_sheet = wb.active

    report_date = data.get("report_date", "17-08-2026")
    total_students = data.get("total_students", 0)
    current_sess = data.get("current_session", {})
    last_sess = data.get("last_session", {})
    curr_contest_name = current_sess.get("contest_name", "Weekly Contest")
    last_contest_name = last_sess.get("contest_name", "Weekly Contest")

    # Palette: Professional Institutional Restrained Navy/Slate
    navy_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    brand_fill = PatternFill(start_color="2563EB", end_color="2563EB", fill_type="solid")
    sub_header_fill = PatternFill(start_color="E2E8F0", end_color="E2E8F0", fill_type="solid")
    section_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")
    zebra_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")

    font_title = Font(name="Times New Roman", size=13, bold=True, color="FFFFFF")
    font_subtitle = Font(name="Times New Roman", size=10, italic=True, color="F8FAFC")
    font_section = Font(name="Times New Roman", size=11, bold=True, color="0F172A")
    font_tbl_head = Font(name="Times New Roman", size=9.5, bold=True, color="0F172A")
    font_bold = Font(name="Times New Roman", size=9.5, bold=True)
    font_regular = Font(name="Times New Roman", size=9.5)

    thin_border_side = Side(style='thin', color='94A3B8')
    grid_border = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)

    align_center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    align_left = Alignment(horizontal='left', vertical='center', wrap_text=True)

    def setup_page_layout(ws):
        ws.page_setup.orientation = ws.ORIENTATION_LANDSCAPE
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.fitToPage = True
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 0
        if hasattr(ws.sheet_properties, 'pageSetUpPr') and ws.sheet_properties.pageSetUpPr is not None:
            ws.sheet_properties.pageSetUpPr.fitToPage = True

    def add_banner(ws, title: str, subtitle: str, coordinator: Optional[str] = None, max_col_letter: str = 'H'):
        ws.merge_cells(f'A1:{max_col_letter}1')
        ws.merge_cells(f'A2:{max_col_letter}2')
        
        c1 = ws['A1']
        c1.value = f"NANDHA ENGINEERING COLLEGE (AUTONOMOUS) — {title}"
        c1.font = font_title
        c1.fill = navy_fill
        c1.alignment = align_center

        coord_text = f" | Coordinator: {coordinator}" if coordinator else ""
        c2 = ws['A2']
        c2.value = f"{subtitle} | Date: {report_date}{coord_text} | Total Students: {total_students}"
        c2.font = font_subtitle
        c2.fill = brand_fill
        c2.alignment = align_center

        ws.row_dimensions[1].height = 26
        ws.row_dimensions[2].height = 20

    def apply_col_widths(ws, width_map: Dict[str, int]):
        for col_letter, width in width_map.items():
            ws.column_dimensions[col_letter].width = width

    DASH = "-"

    def format_solved_str(public_result: str, student_dict: Dict[str, Any]) -> Tuple[str, str]:
        res = public_result or "NOT_PARTICIPATED"
        if res == "4_SOLVED":
            return "PUBLIC", "4/4"
        elif res == "3_SOLVED":
            return "PUBLIC", "3/4"
        elif res == "2_SOLVED":
            return "PUBLIC", "2/4"
        elif res == "1_SOLVED":
            return "PUBLIC", "1/4"
        elif res == "0_SOLVED":
            return "PUBLIC", "0/4"
        elif res in ("NOT_PARTICIPATED", "NOT_ATTENDED"):
            return "NOT ATTENDED", DASH
        elif res == "UNKNOWN":
            return "UNKNOWN", DASH
        elif res == "PENDING":
            return "PENDING", DASH
        elif res == "SOURCE_UNAVAILABLE":
            return "SOURCE UNAVAILABLE", DASH
        else:
            return str(res), DASH

    all_students = data.get("all_students_current", [])

    # ─────────────────────────────────────────────────────────────────────────────
    # SHEET 01: 01_CSE_CS_Matrix
    # ─────────────────────────────────────────────────────────────────────────────
    ws01 = wb.create_sheet(title="01_CSE_CS_Matrix")
    setup_page_layout(ws01)
    coord_cs = get_coordinator_for_department("CSE(CS)")
    add_banner(
        ws01,
        "DEPARTMENT OF COMPUTER SCIENCE & ENGINEERING (CYBER SECURITY)",
        f"Contest: {curr_contest_name}",
        coordinator=coord_cs,
        max_col_letter='H'
    )

    headers_dept = ["S.No", "Register No", "Student Name", "Year", "Batch", "Username", "Public Result", "Solved"]
    ws01.row_dimensions[4].height = 24
    for col_idx, h in enumerate(headers_dept, start=1):
        c = ws01.cell(row=4, column=col_idx, value=h)
        c.font = font_tbl_head
        c.fill = sub_header_fill
        c.alignment = align_center
        c.border = grid_border

    cs_students = [s for s in all_students if s.get("dept") == "CSE(CS)"]
    for r_i, s in enumerate(cs_students, start=5):
        ws01.row_dimensions[r_i].height = 20
        res_disp, solved_disp = format_solved_str(s.get("public_result"), s)
        row_vals = [
            r_i - 4,
            s.get("reg_no"),
            s.get("name"),
            s.get("year"),
            s.get("batch"),
            s.get("username") or DASH,
            res_disp,
            solved_disp
        ]
        for c_i, val in enumerate(row_vals, start=1):
            cell = ws01.cell(row=r_i, column=c_i, value=val)
            cell.font = font_bold if c_i == 3 else font_regular
            cell.border = grid_border
            cell.alignment = align_left if c_i in (3, 6) else align_center
            if r_i % 2 == 0:
                cell.fill = zebra_fill
    
    apply_col_widths(ws01, {'A': 8, 'B': 18, 'C': 28, 'D': 10, 'E': 15, 'F': 24, 'G': 18, 'H': 12})
    ws01.freeze_panes = 'A5'
    ws01.auto_filter.ref = f"A4:H{len(cs_students)+4}"
    ws01.print_title_rows = '4:4'

    # ─────────────────────────────────────────────────────────────────────────────
    # SHEET 02: 02_CSE_IOT_Matrix
    # ─────────────────────────────────────────────────────────────────────────────
    ws02 = wb.create_sheet(title="02_CSE_IOT_Matrix")
    setup_page_layout(ws02)
    coord_iot = get_coordinator_for_department("CSE(IOT)")
    add_banner(
        ws02,
        "DEPARTMENT OF COMPUTER SCIENCE & ENGINEERING (IOT)",
        f"Contest: {curr_contest_name}",
        coordinator=coord_iot,
        max_col_letter='H'
    )

    ws02.row_dimensions[4].height = 24
    for col_idx, h in enumerate(headers_dept, start=1):
        c = ws02.cell(row=4, column=col_idx, value=h)
        c.font = font_tbl_head
        c.fill = sub_header_fill
        c.alignment = align_center
        c.border = grid_border

    iot_students = [s for s in all_students if s.get("dept") == "CSE(IOT)"]
    for r_i, s in enumerate(iot_students, start=5):
        ws02.row_dimensions[r_i].height = 20
        res_disp, solved_disp = format_solved_str(s.get("public_result"), s)
        row_vals = [
            r_i - 4,
            s.get("reg_no"),
            s.get("name"),
            s.get("year"),
            s.get("batch"),
            s.get("username") or DASH,
            res_disp,
            solved_disp
        ]
        for c_i, val in enumerate(row_vals, start=1):
            cell = ws02.cell(row=r_i, column=c_i, value=val)
            cell.font = font_bold if c_i == 3 else font_regular
            cell.border = grid_border
            cell.alignment = align_left if c_i in (3, 6) else align_center
            if r_i % 2 == 0:
                cell.fill = zebra_fill

    apply_col_widths(ws02, {'A': 8, 'B': 18, 'C': 28, 'D': 10, 'E': 15, 'F': 24, 'G': 18, 'H': 12})
    ws02.freeze_panes = 'A5'
    ws02.auto_filter.ref = f"A4:H{len(iot_students)+4}"
    ws02.print_title_rows = '4:4'

    # ─────────────────────────────────────────────────────────────────────────────
    # SHEETS 03-05: Year-wise Matrices (II, III, IV)
    # ─────────────────────────────────────────────────────────────────────────────
    year_sheets = [
        ("03_II_Year", "II", "SECOND YEAR (BATCH 2025 - 2029)"),
        ("04_III_Year", "III", "THIRD YEAR (BATCH 2024 - 2028)"),
        ("05_IV_Year", "IV", "FOURTH YEAR (BATCH 2023 - 2027)"),
    ]

    headers_year = ["S.No", "Register No", "Student Name", "Department", "Year", "Batch", "Username", "Public Result", "Solved"]

    for sheet_name, yr_code, yr_title in year_sheets:
        ws_yr = wb.create_sheet(title=sheet_name)
        setup_page_layout(ws_yr)
        add_banner(
            ws_yr,
            yr_title,
            f"Contest: {curr_contest_name}",
            max_col_letter='I'
        )

        ws_yr.row_dimensions[4].height = 24
        for col_idx, h in enumerate(headers_year, start=1):
            c = ws_yr.cell(row=4, column=col_idx, value=h)
            c.font = font_tbl_head
            c.fill = sub_header_fill
            c.alignment = align_center
            c.border = grid_border

        yr_students = [s for s in all_students if s.get("year") == yr_code]
        for r_i, s in enumerate(yr_students, start=5):
            ws_yr.row_dimensions[r_i].height = 20
            res_disp, solved_disp = format_solved_str(s.get("public_result"), s)
            row_vals = [
                r_i - 4,
                s.get("reg_no"),
                s.get("name"),
                s.get("dept"),
                s.get("year"),
                s.get("batch"),
                s.get("username") or DASH,
                res_disp,
                solved_disp
            ]
            for c_i, val in enumerate(row_vals, start=1):
                cell = ws_yr.cell(row=r_i, column=c_i, value=val)
                cell.font = font_bold if c_i == 3 else font_regular
                cell.border = grid_border
                cell.alignment = align_left if c_i in (3, 7) else align_center
                if r_i % 2 == 0:
                    cell.fill = zebra_fill

        apply_col_widths(ws_yr, {'A': 8, 'B': 18, 'C': 28, 'D': 18, 'E': 10, 'F': 15, 'G': 24, 'H': 18, 'I': 12})
        ws_yr.freeze_panes = 'A5'
        if yr_students:
            ws_yr.auto_filter.ref = f"A4:I{len(yr_students)+4}"
        ws_yr.print_title_rows = '4:4'

    # ─────────────────────────────────────────────────────────────────────────────
    # SHEET 06: 06_Overall_Summary
    # ─────────────────────────────────────────────────────────────────────────────
    ws06 = wb.create_sheet(title="06_Overall_Summary")
    setup_page_layout(ws06)
    add_banner(
        ws06,
        "OVERALL WEEKLY PERFORMANCE SUMMARY DASHBOARD",
        f"Contest: {curr_contest_name}",
        max_col_letter='L'
    )

    curr_row = 4

    # 1. REPORT INFORMATION
    ws06.merge_cells(f'A{curr_row}:D{curr_row}')
    ws06[f'A{curr_row}'] = "REPORT INFORMATION"
    ws06[f'A{curr_row}'].font = font_section
    ws06[f'A{curr_row}'].fill = sub_header_fill
    curr_row += 1

    info_rows = [
        ("Report Date", report_date, "Resolution Mode", "db_auto"),
        ("Current Contest", curr_contest_name, "Last Contest", last_contest_name)
    ]
    for r_vals in info_rows:
        ws06.row_dimensions[curr_row].height = 20
        ws06.cell(row=curr_row, column=1, value=r_vals[0]).font = font_bold
        ws06.cell(row=curr_row, column=2, value=r_vals[1]).font = font_regular
        ws06.cell(row=curr_row, column=3, value=r_vals[2]).font = font_bold
        ws06.cell(row=curr_row, column=4, value=r_vals[3]).font = font_regular
        for col_i in range(1, 5):
            ws06.cell(row=curr_row, column=col_i).border = grid_border
        curr_row += 1

    curr_row += 1

    # 2. COLLEGE SUMMARY & SOLVED DISTRIBUTION
    coll_metrics = data.get("college_summary", {}).get("metrics", {})
    cw_metrics = coll_metrics.get("current_week", {})
    vir_metrics = coll_metrics.get("virtual_contest", {})

    ws06.merge_cells(f'A{curr_row}:L{curr_row}')
    ws06[f'A{curr_row}'] = "COLLEGE CONTEST PARTICIPATION & SOLVED DISTRIBUTION"
    ws06[f'A{curr_row}'].font = font_section
    ws06[f'A{curr_row}'].fill = sub_header_fill
    curr_row += 1

    coll_headers = [
        "Total Students", "Public Participated", "Virtual Participated", "Not Attended",
        "Pending", "Unknown", "Source Unavailable",
        "4 Solved", "3 Solved", "2 Solved", "1 Solved", "0 Solved"
    ]
    ws06.row_dimensions[curr_row].height = 22
    for c_idx, h in enumerate(coll_headers, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=h)
        c.font = font_tbl_head
        c.fill = section_fill
        c.alignment = align_center
        c.border = grid_border
    curr_row += 1

    pub_part = cw_metrics.get("q4", 0) + cw_metrics.get("q3", 0) + cw_metrics.get("q2", 0) + cw_metrics.get("q1", 0) + cw_metrics.get("q0", 0)
    vir_part = vir_metrics.get("q4", 0) + vir_metrics.get("q3", 0) + vir_metrics.get("q2", 0) + vir_metrics.get("q1", 0) + vir_metrics.get("q0", 0)

    coll_vals = [
        total_students,
        pub_part,
        vir_part,
        cw_metrics.get("not_participated", 0),
        0,  # Pending
        cw_metrics.get("unknown", 0),
        cw_metrics.get("source_unavailable", 0),
        cw_metrics.get("q4", 0),
        cw_metrics.get("q3", 0),
        cw_metrics.get("q2", 0),
        cw_metrics.get("q1", 0),
        cw_metrics.get("q0", 0)
    ]
    ws06.row_dimensions[curr_row].height = 20
    for c_idx, val in enumerate(coll_vals, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=val)
        c.font = font_bold
        c.alignment = align_center
        c.border = grid_border
    curr_row += 2

    # 3. DEPARTMENT SUMMARY
    ws06.merge_cells(f'A{curr_row}:K{curr_row}')
    ws06[f'A{curr_row}'] = "DEPARTMENT-WISE SUMMARY"
    ws06[f'A{curr_row}'].font = font_section
    ws06[f'A{curr_row}'].fill = sub_header_fill
    curr_row += 1

    dept_headers = [
        "Department", "Total Students", "Public Participated", "Not Attended",
        "Pending", "Unknown", "4 Solved", "3 Solved", "2 Solved", "1 Solved", "0 Solved"
    ]
    ws06.row_dimensions[curr_row].height = 22
    for c_idx, h in enumerate(dept_headers, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=h)
        c.font = font_tbl_head
        c.fill = section_fill
        c.alignment = align_center
        c.border = grid_border
    curr_row += 1

    for d in data.get("dept_summaries", []):
        dm = d.get("current_week", {})
        d_pub_part = dm.get("q4", 0) + dm.get("q3", 0) + dm.get("q2", 0) + dm.get("q1", 0) + dm.get("q0", 0)
        row_vals = [
            d.get("department_name", d.get("department")),
            d.get("total_students", 0),
            d_pub_part,
            dm.get("not_participated", 0),
            0,  # Pending
            dm.get("unknown", 0),
            dm.get("q4", 0),
            dm.get("q3", 0),
            dm.get("q2", 0),
            dm.get("q1", 0),
            dm.get("q0", 0)
        ]
        ws06.row_dimensions[curr_row].height = 20
        for c_idx, val in enumerate(row_vals, start=1):
            c = ws06.cell(row=curr_row, column=c_idx, value=val)
            c.font = font_bold if c_idx == 1 else font_regular
            c.alignment = align_left if c_idx == 1 else align_center
            c.border = grid_border
        curr_row += 1

    curr_row += 1

    # 4. YEAR SUMMARY (Only II, III, IV)
    ws06.merge_cells(f'A{curr_row}:L{curr_row}')
    ws06[f'A{curr_row}'] = "YEAR-WISE SUMMARY"
    ws06[f'A{curr_row}'].font = font_section
    ws06[f'A{curr_row}'].fill = sub_header_fill
    curr_row += 1

    year_headers = [
        "Year", "Batch", "Students", "Public Participated", "Not Attended",
        "Pending", "Unknown", "4 Solved", "3 Solved", "2 Solved", "1 Solved", "0 Solved"
    ]
    ws06.row_dimensions[curr_row].height = 22
    for c_idx, h in enumerate(year_headers, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=h)
        c.font = font_tbl_head
        c.fill = section_fill
        c.alignment = align_center
        c.border = grid_border
    curr_row += 1

    for b in data.get("batch_summaries", []):
        if b.get("total_students", 0) == 0 or b.get("year") == "I":
            continue
        bm = b.get("current_week", {})
        b_pub_part = bm.get("q4", 0) + bm.get("q3", 0) + bm.get("q2", 0) + bm.get("q1", 0) + bm.get("q0", 0)
        row_vals = [
            b.get("year"),
            b.get("batch"),
            b.get("total_students", 0),
            b_pub_part,
            bm.get("not_participated", 0),
            0,
            bm.get("unknown", 0),
            bm.get("q4", 0),
            bm.get("q3", 0),
            bm.get("q2", 0),
            bm.get("q1", 0),
            bm.get("q0", 0)
        ]
        ws06.row_dimensions[curr_row].height = 20
        for c_idx, val in enumerate(row_vals, start=1):
            c = ws06.cell(row=curr_row, column=c_idx, value=val)
            c.font = font_bold if c_idx <= 2 else font_regular
            c.alignment = align_center
            c.border = grid_border
        curr_row += 1

    curr_row += 1

    # 5. PUBLIC VS VIRTUAL SUMMARY
    ws06.merge_cells(f'A{curr_row}:J{curr_row}')
    ws06[f'A{curr_row}'] = "PUBLIC VS VIRTUAL CONTEST SUMMARY"
    ws06[f'A{curr_row}'].font = font_section
    ws06[f'A{curr_row}'].fill = sub_header_fill
    curr_row += 1

    pv_headers = [
        "Type", "Participated", "Not Participated", "Pending", "Unknown",
        "4 Solved", "3 Solved", "2 Solved", "1 Solved", "0 Solved"
    ]
    ws06.row_dimensions[curr_row].height = 22
    for c_idx, h in enumerate(pv_headers, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=h)
        c.font = font_tbl_head
        c.fill = section_fill
        c.alignment = align_center
        c.border = grid_border
    curr_row += 1

    # Public Row
    pub_row_vals = [
        "Public Contest", pub_part, cw_metrics.get("not_participated", 0), 0, cw_metrics.get("unknown", 0),
        cw_metrics.get("q4", 0), cw_metrics.get("q3", 0), cw_metrics.get("q2", 0), cw_metrics.get("q1", 0), cw_metrics.get("q0", 0)
    ]
    ws06.row_dimensions[curr_row].height = 20
    for c_idx, val in enumerate(pub_row_vals, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=val)
        c.font = font_bold if c_idx == 1 else font_regular
        c.alignment = align_left if c_idx == 1 else align_center
        c.border = grid_border
    curr_row += 1

    # Virtual Row
    vir_row_vals = [
        "Virtual Contest", vir_part, total_students - vir_part, 0, 0,
        vir_metrics.get("q4", 0), vir_metrics.get("q3", 0), vir_metrics.get("q2", 0), vir_metrics.get("q1", 0), vir_metrics.get("q0", 0)
    ]
    ws06.row_dimensions[curr_row].height = 20
    for c_idx, val in enumerate(vir_row_vals, start=1):
        c = ws06.cell(row=curr_row, column=c_idx, value=val)
        c.font = font_bold if c_idx == 1 else font_regular
        c.alignment = align_left if c_idx == 1 else align_center
        c.border = grid_border
    curr_row += 1

    apply_col_widths(ws06, {'A': 25, 'B': 20, 'C': 18, 'D': 16, 'E': 14, 'F': 14, 'G': 18, 'H': 12, 'I': 12, 'J': 12, 'K': 12, 'L': 12})
    ws06.freeze_panes = 'A4'

    # ─────────────────────────────────────────────────────────────────────────────
    # SHEET 07: 07_Not_Attended
    # ─────────────────────────────────────────────────────────────────────────────
    ws07 = wb.create_sheet(title="07_Not_Attended")
    setup_page_layout(ws07)
    add_banner(
        ws07,
        "NON-PARTICIPATING & UNRESOLVED STUDENTS AUDIT",
        f"Contest: {curr_contest_name}",
        max_col_letter='I'
    )

    headers_na = ["S.No", "Register No", "Student Name", "Department", "Year", "Batch", "Username", "Status", "Reason"]
    ws07.row_dimensions[4].height = 24
    for col_idx, h in enumerate(headers_na, start=1):
        c = ws07.cell(row=4, column=col_idx, value=h)
        c.font = font_tbl_head
        c.fill = sub_header_fill
        c.alignment = align_center
        c.border = grid_border

    # Categorize non-participating students cleanly into sections
    na_groups = {
        "NOT ATTENDED": [],
        "PENDING": [],
        "UNKNOWN": [],
        "SOURCE UNAVAILABLE": []
    }

    for s in all_students:
        res = s.get("public_result", "NOT_PARTICIPATED")
        if res in ("NOT_PARTICIPATED", "NOT_ATTENDED"):
            na_groups["NOT ATTENDED"].append((s, "Student did not participate in Weekly Contest"))
        elif res == "PENDING":
            na_groups["PENDING"].append((s, "Data fetch / classification in progress"))
        elif res == "UNKNOWN":
            reason = s.get("fetch_error") or "LeetCode profile not found / invalid username"
            na_groups["UNKNOWN"].append((s, reason))
        elif res == "SOURCE_UNAVAILABLE":
            reason = s.get("fetch_error") or "LeetCode source unavailable / network failure"
            na_groups["SOURCE UNAVAILABLE"].append((s, reason))

    curr_r = 5
    s_no = 1
    for grp_status in ["NOT ATTENDED", "PENDING", "UNKNOWN", "SOURCE UNAVAILABLE"]:
        s_list = na_groups[grp_status]
        if not s_list:
            continue

        # Group Section Header Row
        ws07.merge_cells(f'A{curr_r}:I{curr_r}')
        sec_c = ws07.cell(row=curr_r, column=1, value=f"STATUS: {grp_status} ({len(s_list)} Students)")
        sec_c.font = font_section
        sec_c.fill = section_fill
        sec_c.alignment = align_left
        ws07.row_dimensions[curr_r].height = 22
        curr_r += 1

        for s, reason in s_list:
            ws07.row_dimensions[curr_r].height = 20
            row_vals = [
                s_no,
                s.get("reg_no"),
                s.get("name"),
                s.get("dept"),
                s.get("year"),
                s.get("batch"),
                s.get("username") or DASH,
                grp_status,
                reason
            ]
            for c_i, val in enumerate(row_vals, start=1):
                cell = ws07.cell(row=curr_r, column=c_i, value=val)
                cell.font = font_bold if c_i == 3 else font_regular
                cell.border = grid_border
                cell.alignment = align_left if c_i in (3, 7, 9) else align_center
                if curr_r % 2 == 0:
                    cell.fill = zebra_fill
            curr_r += 1
            s_no += 1

    apply_col_widths(ws07, {
        'A': 8,   # S.No
        'B': 18,  # Register No
        'C': 28,  # Student Name
        'D': 18,  # Department
        'E': 10,  # Year
        'F': 15,  # Batch
        'G': 24,  # Username
        'H': 20,  # Status
        'I': 35   # Reason
    })
    ws07.freeze_panes = 'A5'
    if s_no > 1:
        ws07.auto_filter.ref = f"A4:I{curr_r-1}"
    ws07.print_title_rows = '4:4'

    # Remove default worksheet
    if default_sheet in wb.worksheets:
        wb.remove(default_sheet)

    # ─────────────────────────────────────────────────────────────────────────────
    # SAVE WORKBOOK
    # ─────────────────────────────────────────────────────────────────────────────
    try:
        wb.save(filepath)
        return filepath
    except PermissionError:
        import datetime
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        base, ext = os.path.splitext(filepath)
        fallback_path = f"{base}_{timestamp}{ext}"
        wb.save(fallback_path)
        print(f"\nWARNING: Destination file '{os.path.basename(filepath)}' is locked. Saved to {fallback_path}")
        return fallback_path
