import pytest
import datetime
from zoneinfo import ZoneInfo
from backend.database import SessionLocal
from backend.models import Student, WeeklyPublicResult
from backend.services.master_contest_reconstruction_engine import MasterContestReconstructionEngine
from backend.services.contest_problem_accuracy_engine import ContestProblemAccuracyEngine, normalize_slug, is_accepted_submission
from backend.contest_truth_engine import ContestTruthEngine

IST = ZoneInfo("Asia/Kolkata")
UTC = datetime.timezone.utc

def test_ragavan_q4_contest_520_reconstruction():
    """
    Regression Test for Ragavan S (732223CC043) Contest 520 Q4 Detection & Reconstruction.
    Verifies that submission 2147254002 for 'Lexicographically Largest Power Array' is correctly
    matched, inside the contest window, ACCEPTED, and results in Q1=1, Q2=1, Q3=1, Q4=1, TOTAL=4.
    """
    db = SessionLocal()
    try:
        student = db.query(Student).filter(Student.reg_no == "732223CC043").first()
        assert student is not None, "Student 732223CC043 (RAGAVAN S) must exist in database"
        assert student.username == "23cc043", "Student username must be 23cc043"

        # 1. Verify GQL evidence / submission 2147254002 via ContestTruthEngine
        truth_engine = ContestTruthEngine(db_connection=db)
        
        mock_raw_data = {
            "userContestRankingHistory": [
                {
                    "attended": True,
                    "problemsSolved": 4,
                    "totalProblems": 4,
                    "contest": {"title": "Weekly Contest 520"}
                }
            ],
            "recentAcSubmissionList": [
                {
                    "id": "2147174555",
                    "title": "Number of Intersecting Interval Pairs I",
                    "titleSlug": "number-of-intersecting-interval-pairs-i",
                    "timestamp": 1789872769,
                    "statusDisplay": "Accepted"
                },
                {
                    "id": "2147186867",
                    "title": "Number of Intersecting Interval Pairs II",
                    "titleSlug": "number-of-intersecting-interval-pairs-ii",
                    "timestamp": 1789873171,
                    "statusDisplay": "Accepted"
                },
                {
                    "id": "2147220817",
                    "title": "Maximum Pulse Value After One Subarray Rotation",
                    "titleSlug": "maximum-pulse-value-after-one-subarray-rotation",
                    "timestamp": 1789874350,
                    "statusDisplay": "Accepted"
                },
                {
                    "id": "2147254002",
                    "title": "Lexicographically Largest Power Array",
                    "titleSlug": "lexicographically-largest-power-array",
                    "timestamp": 1789875649,
                    "statusDisplay": "Accepted"
                }
            ]
        }

        official_slugs = [
            "number-of-intersecting-interval-pairs-i",
            "number-of-intersecting-interval-pairs-ii",
            "maximum-pulse-value-after-one-subarray-rotation",
            "lexicographically-largest-power-array"
        ]

        verification = truth_engine.verify_contest_evidence(
            username=student.username,
            contest_id="weekly-contest-520",
            contest_problems=official_slugs,
            raw_data=mock_raw_data,
            contest_date_str="2026-09-20"
        )

        assert verification["q_matrix"]["Q1"] is True
        assert verification["q_matrix"]["Q2"] is True
        assert verification["q_matrix"]["Q3"] is True
        assert verification["q_matrix"]["Q4"] is True
        assert verification["solved_count"] == 4

        # 2. Run Cohort Reconstruction Engine
        reconstruction_engine = MasterContestReconstructionEngine(db=db)
        reconstruction_results = reconstruction_engine.reconstruct_cohort_results(
            contest_number=520,
            raw_evidence_map={student.username.lower(): mock_raw_data}
        )

        ragavan_row = None
        for r in reconstruction_results.get("official_result", []):
            if r.get("reg_no") == "732223CC043":
                ragavan_row = r
                break

        assert ragavan_row is not None, "Ragavan S official row must be generated by reconstruction engine"
        assert ragavan_row["q1"] == 1
        assert ragavan_row["q2"] == 1
        assert ragavan_row["q3"] == 1
        assert ragavan_row["q4"] == 1
        assert ragavan_row["total_contest_solved"] == 4
        assert ragavan_row["total_contest_solved"] == (
            ragavan_row["q1"] + ragavan_row["q2"] + ragavan_row["q3"] + ragavan_row["q4"]
        )

        # Assert submission 2147254002 is the specific evidence responsible for Q4 = 1
        q4_audit = None
        for audit_row in reconstruction_results.get("evidence_audit", []):
            if (
                audit_row.get("reg_no") == "732223CC043"
                and audit_row.get("question_number") == 4
                and audit_row.get("submission_id") == "2147254002"
            ):
                q4_audit = audit_row
                break

        assert q4_audit is not None, "Evidence audit log must contain submission 2147254002 for Q4"
        assert q4_audit["is_within_contest_window"] is True
        assert q4_audit["is_contest_problem"] is True
        assert q4_audit["is_verified"] is True

        # 3. Reconstructed Result Assertion
        assert ragavan_row["q1"] == 1
        assert ragavan_row["q2"] == 1
        assert ragavan_row["q3"] == 1
        assert ragavan_row["q4"] == 1
        assert ragavan_row["total_contest_solved"] == 4
        assert ragavan_row["total_contest_solved"] == (ragavan_row["q1"] + ragavan_row["q2"] + ragavan_row["q3"] + ragavan_row["q4"])

    finally:
        db.close()
