import pytest
import datetime
from zoneinfo import ZoneInfo
from backend.database import SessionLocal
from backend.models import Student, WeeklyPublicResult
from backend.services.master_contest_reconstruction_engine import MasterContestReconstructionEngine
from backend.contest_truth_engine import ContestTruthEngine

def test_nanthish_q3_contest_520_reconstruction():
    """
    Regression Test for Nanthish S (732224CC031) Contest 520 Q3 Detection & Reconstruction.
    Verifies that Q1=1, Q2=1, Q3=1, Q4=0, TOTAL=3 is preserved.
    """
    db = SessionLocal()
    try:
        student = db.query(Student).filter(Student.reg_no == "732224CC031").first()
        assert student is not None, "Student 732224CC031 (NANTHISH S) must exist in database"

        truth_engine = ContestTruthEngine(db_connection=db)
        
        mock_raw_data = {
            "userContestRankingHistory": [
                {
                    "attended": True,
                    "problemsSolved": 3,
                    "totalProblems": 4,
                    "contest": {"title": "Weekly Contest 520"}
                }
            ],
            "recentAcSubmissionList": [
                {
                    "id": "2147174000",
                    "title": "Number of Intersecting Interval Pairs I",
                    "titleSlug": "number-of-intersecting-interval-pairs-i",
                    "timestamp": 1789872769,
                    "statusDisplay": "Accepted"
                },
                {
                    "id": "2147186000",
                    "title": "Number of Intersecting Interval Pairs II",
                    "titleSlug": "number-of-intersecting-interval-pairs-ii",
                    "timestamp": 1789873171,
                    "statusDisplay": "Accepted"
                },
                {
                    "id": "2147220000",
                    "title": "Maximum Pulse Value After One Subarray Rotation",
                    "titleSlug": "maximum-pulse-value-after-one-subarray-rotation",
                    "timestamp": 1789874350,
                    "statusDisplay": "Accepted"
                }
            ]
        }

        official_slugs = [
            "number-of-intersecting-interval-pairs-i",
            "number-of-intersecting-interval-pairs-ii",
            "maximum-pulse-value-after-one-subarray-rotation",
            "lexicographically-largest-power-array"
        ]

        verification = truth_engine.verify_contest_evidence(
            username=student.username,
            contest_id="weekly-contest-520",
            contest_problems=official_slugs,
            raw_data=mock_raw_data,
            contest_date_str="2026-09-20"
        )

        assert verification["q_matrix"]["Q1"] is True
        assert verification["q_matrix"]["Q2"] is True
        assert verification["q_matrix"]["Q3"] is True
        assert verification["q_matrix"]["Q4"] is False
        assert verification["solved_count"] == 3

        reconstruction_engine = MasterContestReconstructionEngine(db=db)
        reconstruction_results = reconstruction_engine.reconstruct_cohort_results(
            contest_number=520,
            raw_evidence_map={student.username.lower(): mock_raw_data}
        )

        nanthish_row = None
        for r in reconstruction_results.get("official_result", []):
            if r.get("reg_no") == "732224CC031":
                nanthish_row = r
                break

        assert nanthish_row is not None, "Nanthish S official row must be generated by reconstruction engine"
        assert nanthish_row["q1"] == 1
        assert nanthish_row["q2"] == 1
        assert nanthish_row["q3"] == 1
        assert nanthish_row["q4"] == 0
        assert nanthish_row["total_contest_solved"] == 3
        assert nanthish_row["total_contest_solved"] == (
            nanthish_row["q1"] + nanthish_row["q2"] + nanthish_row["q3"] + nanthish_row["q4"]
        )

        res = db.query(WeeklyPublicResult).filter(
            WeeklyPublicResult.student_id == student.id,
            WeeklyPublicResult.session_id == 18
        ).first()

        if res:
            assert res.q1 == 1
            assert res.q2 == 1
            assert res.q3 == 1
            assert res.q4 == 0
            assert res.total_contest_solved == 3

    finally:
        db.close()
