"""Add participant entry time

Revision ID: 442de0a8ddc5
Revises: 7de62f37279a
Create Date: 2026-09-24 21:29:56.887809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442de0a8ddc5'
down_revision: Union[str, Sequence[str], None] = '7de62f37279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_logs', 'event_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('admin_audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'denial_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'event_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'previous_event_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'institution_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'NEC_AUTONOMOUS_001'"))
    op.alter_column('admin_audit_logs', 'institution_logo_reference',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'assets/nec_logo.png'"))
    op.drop_index(op.f('idx_audit_correlation_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('idx_audit_event_timestamp'), table_name='admin_audit_logs')
    op.drop_index(op.f('idx_audit_trace_id'), table_name='admin_audit_logs')
    op.create_index(op.f('ix_admin_audit_logs_event_timestamp'), 'admin_audit_logs', ['event_timestamp'], unique=False)
    op.drop_index(op.f('idx_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_index(op.f('idx_admin_sessions_token_hash'), table_name='admin_sessions')
    op.alter_column('authorized_signatures', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_authorized_signatures_id'), 'authorized_signatures', ['id'], unique=False)
    op.alter_column('certificate_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('certificate_records', 'document_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'CERTIFICATE_OF_EXCELLENCE'"))
    op.drop_index(op.f('ix_certificate_records_verification_id'), table_name='certificate_records')
    op.create_index(op.f('ix_certificate_records_verification_id'), 'certificate_records', ['verification_id'], unique=True)
    op.create_index(op.f('ix_certificate_records_id'), 'certificate_records', ['id'], unique=False)
    op.create_index(op.f('ix_contest_participations_source_username'), 'contest_participations', ['source_username'], unique=False)
    op.drop_index(op.f('idx_email_otp_created_at'), table_name='email_otp_records')
    op.drop_index(op.f('idx_email_otp_email_hash'), table_name='email_otp_records')
    op.drop_index(op.f('idx_email_otp_request_id'), table_name='email_otp_records')
    op.create_index(op.f('ix_email_otp_records_request_ip_hash'), 'email_otp_records', ['request_ip_hash'], unique=False)
    op.alter_column('faculty_action_queue', 'signal_type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ROUTINE_MONITORING'"))
    op.alter_column('faculty_action_queue', 'contest_id',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('faculty_action_queue', 'escalated_to',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_faculty_action_queue_contest_id'), 'faculty_action_queue', ['contest_id'], unique=False)
    op.create_index(op.f('ix_faculty_action_queue_created_at'), 'faculty_action_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_faculty_action_queue_signal_type'), 'faculty_action_queue', ['signal_type'], unique=False)
    op.create_unique_constraint('uq_faculty_action_signal', 'faculty_action_queue', ['student_id', 'signal_type', 'contest_id'])
    op.drop_index(op.f('idx_faculty_assign_fac_stud'), table_name='faculty_student_assignments')
    op.drop_index(op.f('idx_faculty_assign_stud'), table_name='faculty_student_assignments')
    op.create_index(op.f('ix_leetcode_accounts_id'), 'leetcode_accounts', ['id'], unique=False)
    op.alter_column('leetcode_profile_stats', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'success'"))
    op.alter_column('leetcode_profile_stats', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_lps_stud_solved_rating'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('idx_profile_stats_contest_rating'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('idx_profile_stats_student_id'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('idx_profile_stats_sync_solved'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('idx_profile_stats_sync_status'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('idx_profile_stats_total_solved'), table_name='leetcode_profile_stats')
    op.create_index(op.f('ix_leetcode_profile_stats_sync_status'), 'leetcode_profile_stats', ['sync_status'], unique=False)
    op.create_index(op.f('ix_leetcode_profile_stats_total_solved'), 'leetcode_profile_stats', ['total_solved'], unique=False)
    op.create_index(op.f('ix_messages_client_message_id'), 'messages', ['client_message_id'], unique=False)
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index('ix_messages_unread_status', 'messages', ['conversation_id', 'receiver_id', 'status'], unique=False)
    op.alter_column('notification_outbox_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_notification_outbox_events_created_at'), 'notification_outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_events_status'), 'notification_outbox_events', ['status'], unique=False)
    op.drop_column('notification_outbox_events', 'updated_at')
    op.drop_column('notification_outbox_events', 'last_error')
    op.drop_column('notification_outbox_events', 'next_run')
    op.drop_column('notification_outbox_events', 'attempt')
    op.drop_constraint(op.f('uq_official_public_session_student'), 'official_public_participants', type_='unique')
    op.create_index(op.f('ix_official_public_participants_dataset_version'), 'official_public_participants', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_official_public_participants_is_active_version'), 'official_public_participants', ['is_active_version'], unique=False)
    op.create_unique_constraint('uq_official_public_session_student_version', 'official_public_participants', ['session_id', 'student_id', 'dataset_version'])
    op.alter_column('official_weekly_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('official_weekly_snapshots', 'reconciliation_summary',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_official_weekly_snapshots_session_id'), table_name='official_weekly_snapshots')
    op.create_index(op.f('ix_official_weekly_snapshots_id'), 'official_weekly_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_official_weekly_snapshots_session_id'), 'official_weekly_snapshots', ['session_id'], unique=False)
    op.alter_column('password_reset_authorizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_pwd_reset_email'), table_name='password_reset_authorizations')
    op.drop_index(op.f('idx_pwd_reset_hash'), table_name='password_reset_authorizations')
    op.create_index(op.f('ix_password_reset_authorizations_email'), 'password_reset_authorizations', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_authorizations_id'), 'password_reset_authorizations', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_authorizations_reset_token_hash'), 'password_reset_authorizations', ['reset_token_hash'], unique=False)
    op.add_column('previous_week_participation_records', sa.Column('q1_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q2_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q3_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q4_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q1_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q2_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q3_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q4_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q1_time_source', sa.String(length=50), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q2_time_source', sa.String(length=50), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q3_time_source', sa.String(length=50), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('q4_time_source', sa.String(length=50), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('timing_calculation_version', sa.String(length=20), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('timing_calculated_at', sa.DateTime(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('timing_confidence', sa.String(length=20), nullable=True))
    op.drop_column('previous_week_participation_records', 'publish_status')
    op.drop_column('previous_week_participation_records', 'failure_reason')
    op.alter_column('public_contest_sync_audits', 'heartbeat_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('public_contest_sync_audits', 'lock_expiry',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_constraint(op.f('uix_report_cache_key'), 'report_cache', type_='unique')
    op.create_index(op.f('ix_report_cache_filter_hash'), 'report_cache', ['filter_hash'], unique=False)
    op.create_index('ix_report_cache_filter_hash_composite', 'report_cache', ['filter_hash', 'status', 'data_version'], unique=False)
    op.create_index(op.f('ix_report_cache_format'), 'report_cache', ['format'], unique=False)
    op.create_index(op.f('ix_report_cache_report_type'), 'report_cache', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_cache_user_scope'), 'report_cache', ['user_scope'], unique=False)
    op.create_index(op.f('ix_report_jobs_department_id'), 'report_jobs', ['department_id'], unique=False)
    op.create_index(op.f('ix_report_jobs_institution_id'), 'report_jobs', ['institution_id'], unique=False)
    op.alter_column('scheduled_job_executions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('scheduled_job_executions', 'updated_at')
    op.drop_column('scheduled_job_executions', 'created_at')
    op.drop_column('scheduled_job_executions', 'attempt')
    op.alter_column('student_contest_participations', 'score_display',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('student_contest_participations', 'solved_problems',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('student_contest_participations', 'confidence',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text("'HIGH'"))
    op.alter_column('student_contest_participations', 'verification_evidence',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_contest_part_stud_status'), table_name='student_contest_participations')
    op.drop_index(op.f('idx_scp_stud_contest'), table_name='student_contest_participations')
    op.create_index(op.f('ix_student_contest_participations_is_frozen'), 'student_contest_participations', ['is_frozen'], unique=False)
    op.create_index(op.f('ix_student_contest_participations_official_attendance_state'), 'student_contest_participations', ['official_attendance_state'], unique=False)
    op.create_index(op.f('ix_student_contest_participations_verification_level'), 'student_contest_participations', ['verification_level'], unique=False)
    op.drop_column('student_contest_participations', 'is_virtual_attended')
    op.drop_column('student_contest_participations', 'is_public_attended')
    op.alter_column('student_risk_profiles', 'calculation_version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_stat_snapshots_stud_captured'), table_name='student_stat_snapshots')
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('students', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_students_active_dept_year'), table_name='students')
    op.drop_index(op.f('idx_students_department_id'), table_name='students')
    op.drop_index(op.f('idx_students_dept_year'), table_name='students')
    op.drop_index(op.f('idx_students_email'), table_name='students')
    op.drop_index(op.f('idx_students_is_active'), table_name='students')
    op.drop_index(op.f('idx_students_name'), table_name='students')
    op.drop_index(op.f('idx_students_reg_no'), table_name='students')
    op.drop_index(op.f('idx_students_username'), table_name='students')
    op.drop_index(op.f('idx_students_year_level'), table_name='students')
    op.drop_index(op.f('ix_students_search_optimized'), table_name='students')
    op.drop_index(op.f('ix_students_username_unique'), table_name='students', sqlite_where=sa.text('username IS NOT NULL'))
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_index(op.f('ix_students_accommodation'), 'students', ['accommodation'], unique=False)
    op.create_index(op.f('ix_students_allocation'), 'students', ['allocation'], unique=False)
    op.create_index(op.f('ix_students_batch'), 'students', ['batch'], unique=False)
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_institutional_email'), 'students', ['institutional_email'], unique=True)
    op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=True)
    op.create_index('ix_students_search', 'students', ['name', 'reg_no', 'username'], unique=False)
    op.create_index(op.f('ix_students_section_id'), 'students', ['section_id'], unique=False)
    op.create_index(op.f('ix_students_twelfth_cutoff'), 'students', ['twelfth_cutoff'], unique=False)
    op.create_index(op.f('ix_students_year_level'), 'students', ['year_level'], unique=False)
    op.alter_column('users', 'institutional_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('users', 'last_activity',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_department_id'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.create_index(op.f('ix_users_academic_year'), 'users', ['academic_year'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_institutional_id'), 'users', ['institutional_id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_mentoring_role'), 'users', ['mentoring_role'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_reporting_manager_id'), 'users', ['reporting_manager_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_section_id'), 'users', ['section_id'], unique=False)
    op.create_unique_constraint('uq_live_event_identity', 'weekly_contest_live_events', ['session_id', 'student_id', 'question_id', 'event_type'])
    op.add_column('weekly_public_results', sa.Column('participant_entry_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('weekly_public_results', sa.Column('participant_entry_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('participant_entry_time_confidence', sa.String(length=20), nullable=True))
    op.add_column('weekly_public_results', sa.Column('participant_entry_time_method', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('participant_entry_time_observed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q1_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q2_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q3_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q4_observed_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q1_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q2_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q3_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q4_estimated_seconds', sa.Integer(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q1_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q2_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q3_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('q4_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_public_results', sa.Column('timing_calculation_version', sa.String(length=20), nullable=True))
    op.add_column('weekly_public_results', sa.Column('timing_calculated_at', sa.DateTime(), nullable=True))
    op.add_column('weekly_public_results', sa.Column('timing_confidence', sa.String(length=20), nullable=True))
    op.alter_column('weekly_public_results', 'dept',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('weekly_public_results', 'year',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('weekly_public_results', 'error_reason',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_weekly_public_sess_status'), table_name='weekly_public_results')
    op.drop_index(op.f('idx_weekly_public_sess_stud'), table_name='weekly_public_results')
    op.drop_index(op.f('idx_weekly_public_solved'), table_name='weekly_public_results')
    op.drop_index(op.f('ix_weekly_public_results_session_participation'), table_name='weekly_public_results')
    op.create_index('ix_weekly_public_results_participation', 'weekly_public_results', ['session_id', 'participation_status'], unique=False)
    op.create_index('ix_weekly_public_results_session_student', 'weekly_public_results', ['session_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_weekly_public_results_state'), 'weekly_public_results', ['state'], unique=False)
    op.create_unique_constraint('uq_weekly_public_results_session_student', 'weekly_public_results', ['session_id', 'student_id'])
    op.drop_index(op.f('ix_weekly_report_audits_period'), table_name='weekly_report_audits')
    op.alter_column('weekly_sessions', 'week_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weekly_sessions', 'contest_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'dataset_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'last_synced',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'reconciliation_summary',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'reconciliation_failure_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('weekly_sessions', 'last_error_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'finalized_by',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_weekly_sessions_pipeline_state'), 'weekly_sessions', ['pipeline_state'], unique=False)
    op.create_index(op.f('ix_weekly_sessions_session_code'), 'weekly_sessions', ['session_code'], unique=True)
    op.create_index(op.f('ix_weekly_sessions_session_date'), 'weekly_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_weekly_sessions_status'), 'weekly_sessions', ['status'], unique=False)
    op.alter_column('weekly_student_progress', 'week_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_weekly_prog_college_rank'), table_name='weekly_student_progress')
    op.drop_index(op.f('idx_weekly_prog_stud_id'), table_name='weekly_student_progress')
    op.drop_index(op.f('idx_weekly_prog_total_solved'), table_name='weekly_student_progress')
    op.create_index('ix_weekly_student_progress_student_week', 'weekly_student_progress', ['student_id', 'week_number'], unique=False)
    op.drop_index(op.f('ix_weekly_student_snapshots_period'), table_name='weekly_student_snapshots')
    op.add_column('weekly_virtual_results', sa.Column('participant_entry_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('weekly_virtual_results', sa.Column('participant_entry_time_source', sa.String(length=50), nullable=True))
    op.add_column('weekly_virtual_results', sa.Column('participant_entry_time_confidence', sa.String(length=20), nullable=True))
    op.add_column('weekly_virtual_results', sa.Column('participant_entry_time_method', sa.String(length=50), nullable=True))
    op.add_column('weekly_virtual_results', sa.Column('participant_entry_time_observed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_weekly_virtual_sess_stud'), table_name='weekly_virtual_results')
    op.create_index('ix_weekly_virtual_results_session_student', 'weekly_virtual_results', ['session_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_weekly_virtual_results_state'), 'weekly_virtual_results', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_virtual_results_state'), table_name='weekly_virtual_results')
    op.drop_index('ix_weekly_virtual_results_session_student', table_name='weekly_virtual_results')
    op.create_index(op.f('idx_weekly_virtual_sess_stud'), 'weekly_virtual_results', ['session_id', 'student_id'], unique=False)
    op.drop_column('weekly_virtual_results', 'participant_entry_time_observed_at')
    op.drop_column('weekly_virtual_results', 'participant_entry_time_method')
    op.drop_column('weekly_virtual_results', 'participant_entry_time_confidence')
    op.drop_column('weekly_virtual_results', 'participant_entry_time_source')
    op.drop_column('weekly_virtual_results', 'participant_entry_time')
    op.create_index(op.f('ix_weekly_student_snapshots_period'), 'weekly_student_snapshots', ['reporting_period_id'], unique=False)
    op.drop_index('ix_weekly_student_progress_student_week', table_name='weekly_student_progress')
    op.create_index(op.f('idx_weekly_prog_total_solved'), 'weekly_student_progress', ['total_solved'], unique=False)
    op.create_index(op.f('idx_weekly_prog_stud_id'), 'weekly_student_progress', ['student_id'], unique=False)
    op.create_index(op.f('idx_weekly_prog_college_rank'), 'weekly_student_progress', ['college_rank'], unique=False)
    op.alter_column('weekly_student_progress', 'week_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_weekly_sessions_status'), table_name='weekly_sessions')
    op.drop_index(op.f('ix_weekly_sessions_session_date'), table_name='weekly_sessions')
    op.drop_index(op.f('ix_weekly_sessions_session_code'), table_name='weekly_sessions')
    op.drop_index(op.f('ix_weekly_sessions_pipeline_state'), table_name='weekly_sessions')
    op.alter_column('weekly_sessions', 'finalized_by',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'last_error_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'reconciliation_failure_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('weekly_sessions', 'reconciliation_summary',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'last_synced',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'dataset_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'contest_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('weekly_sessions', 'week_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_weekly_report_audits_period'), 'weekly_report_audits', ['reporting_period_id'], unique=False)
    op.drop_constraint('uq_weekly_public_results_session_student', 'weekly_public_results', type_='unique')
    op.drop_index(op.f('ix_weekly_public_results_state'), table_name='weekly_public_results')
    op.drop_index('ix_weekly_public_results_session_student', table_name='weekly_public_results')
    op.drop_index('ix_weekly_public_results_participation', table_name='weekly_public_results')
    op.create_index(op.f('ix_weekly_public_results_session_participation'), 'weekly_public_results', ['session_id', 'participation_status'], unique=False)
    op.create_index(op.f('idx_weekly_public_solved'), 'weekly_public_results', ['total_contest_solved'], unique=False)
    op.create_index(op.f('idx_weekly_public_sess_stud'), 'weekly_public_results', ['session_id', 'student_id'], unique=False)
    op.create_index(op.f('idx_weekly_public_sess_status'), 'weekly_public_results', ['session_id', 'participation_status'], unique=False)
    op.alter_column('weekly_public_results', 'error_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('weekly_public_results', 'year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('weekly_public_results', 'dept',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('weekly_public_results', 'timing_confidence')
    op.drop_column('weekly_public_results', 'timing_calculated_at')
    op.drop_column('weekly_public_results', 'timing_calculation_version')
    op.drop_column('weekly_public_results', 'q4_time_source')
    op.drop_column('weekly_public_results', 'q3_time_source')
    op.drop_column('weekly_public_results', 'q2_time_source')
    op.drop_column('weekly_public_results', 'q1_time_source')
    op.drop_column('weekly_public_results', 'q4_estimated_seconds')
    op.drop_column('weekly_public_results', 'q3_estimated_seconds')
    op.drop_column('weekly_public_results', 'q2_estimated_seconds')
    op.drop_column('weekly_public_results', 'q1_estimated_seconds')
    op.drop_column('weekly_public_results', 'q4_observed_seconds')
    op.drop_column('weekly_public_results', 'q3_observed_seconds')
    op.drop_column('weekly_public_results', 'q2_observed_seconds')
    op.drop_column('weekly_public_results', 'q1_observed_seconds')
    op.drop_column('weekly_public_results', 'participant_entry_time_observed_at')
    op.drop_column('weekly_public_results', 'participant_entry_time_method')
    op.drop_column('weekly_public_results', 'participant_entry_time_confidence')
    op.drop_column('weekly_public_results', 'participant_entry_time_source')
    op.drop_column('weekly_public_results', 'participant_entry_time')
    op.drop_constraint('uq_live_event_identity', 'weekly_contest_live_events', type_='unique')
    op.drop_index(op.f('ix_users_section_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_reporting_manager_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_mentoring_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_institutional_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_academic_year'), table_name='users')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_department_id'), 'users', ['department_id'], unique=False)
    op.alter_column('users', 'last_activity',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'institutional_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_students_year_level'), table_name='students')
    op.drop_index(op.f('ix_students_twelfth_cutoff'), table_name='students')
    op.drop_index(op.f('ix_students_section_id'), table_name='students')
    op.drop_index('ix_students_search', table_name='students')
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index(op.f('ix_students_institutional_email'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_batch'), table_name='students')
    op.drop_index(op.f('ix_students_allocation'), table_name='students')
    op.drop_index(op.f('ix_students_accommodation'), table_name='students')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=False)
    op.create_index(op.f('ix_students_username_unique'), 'students', ['username'], unique=1, sqlite_where=sa.text('username IS NOT NULL'))
    op.create_index(op.f('ix_students_search_optimized'), 'students', ['name', 'reg_no', 'username'], unique=False)
    op.create_index(op.f('idx_students_year_level'), 'students', ['year_level'], unique=False)
    op.create_index(op.f('idx_students_username'), 'students', ['username'], unique=False)
    op.create_index(op.f('idx_students_reg_no'), 'students', ['reg_no'], unique=False)
    op.create_index(op.f('idx_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('idx_students_is_active'), 'students', ['is_active'], unique=False)
    op.create_index(op.f('idx_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('idx_students_dept_year'), 'students', ['department_id', 'year_level'], unique=False)
    op.create_index(op.f('idx_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('idx_students_active_dept_year'), 'students', ['is_active', 'department_id', 'year_level'], unique=False)
    op.alter_column('students', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('students', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.create_index(op.f('idx_stat_snapshots_stud_captured'), 'student_stat_snapshots', ['student_id', 'captured_at'], unique=False)
    op.alter_column('student_risk_profiles', 'calculation_version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('student_contest_participations', sa.Column('is_public_attended', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('student_contest_participations', sa.Column('is_virtual_attended', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.drop_index(op.f('ix_student_contest_participations_verification_level'), table_name='student_contest_participations')
    op.drop_index(op.f('ix_student_contest_participations_official_attendance_state'), table_name='student_contest_participations')
    op.drop_index(op.f('ix_student_contest_participations_is_frozen'), table_name='student_contest_participations')
    op.create_index(op.f('idx_scp_stud_contest'), 'student_contest_participations', ['student_id', 'contest_id'], unique=False)
    op.create_index(op.f('idx_contest_part_stud_status'), 'student_contest_participations', ['student_id', 'participation_mode', 'official_attendance_state'], unique=False)
    op.alter_column('student_contest_participations', 'verification_evidence',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_contest_participations', 'confidence',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'HIGH'"))
    op.alter_column('student_contest_participations', 'solved_problems',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('student_contest_participations', 'score_display',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('scheduled_job_executions', sa.Column('attempt', sa.INTEGER(), nullable=True))
    op.add_column('scheduled_job_executions', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('scheduled_job_executions', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.alter_column('scheduled_job_executions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_report_jobs_institution_id'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_jobs_department_id'), table_name='report_jobs')
    op.drop_index(op.f('ix_report_cache_user_scope'), table_name='report_cache')
    op.drop_index(op.f('ix_report_cache_report_type'), table_name='report_cache')
    op.drop_index(op.f('ix_report_cache_format'), table_name='report_cache')
    op.drop_index('ix_report_cache_filter_hash_composite', table_name='report_cache')
    op.drop_index(op.f('ix_report_cache_filter_hash'), table_name='report_cache')
    op.create_unique_constraint(op.f('uix_report_cache_key'), 'report_cache', ['institution_id', 'week_id', 'file_type', 'data_version'])
    op.alter_column('public_contest_sync_audits', 'lock_expiry',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('public_contest_sync_audits', 'heartbeat_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.add_column('previous_week_participation_records', sa.Column('failure_reason', sa.TEXT(), nullable=True))
    op.add_column('previous_week_participation_records', sa.Column('publish_status', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('previous_week_participation_records', 'timing_confidence')
    op.drop_column('previous_week_participation_records', 'timing_calculated_at')
    op.drop_column('previous_week_participation_records', 'timing_calculation_version')
    op.drop_column('previous_week_participation_records', 'q4_time_source')
    op.drop_column('previous_week_participation_records', 'q3_time_source')
    op.drop_column('previous_week_participation_records', 'q2_time_source')
    op.drop_column('previous_week_participation_records', 'q1_time_source')
    op.drop_column('previous_week_participation_records', 'q4_estimated_seconds')
    op.drop_column('previous_week_participation_records', 'q3_estimated_seconds')
    op.drop_column('previous_week_participation_records', 'q2_estimated_seconds')
    op.drop_column('previous_week_participation_records', 'q1_estimated_seconds')
    op.drop_column('previous_week_participation_records', 'q4_observed_seconds')
    op.drop_column('previous_week_participation_records', 'q3_observed_seconds')
    op.drop_column('previous_week_participation_records', 'q2_observed_seconds')
    op.drop_column('previous_week_participation_records', 'q1_observed_seconds')
    op.drop_index(op.f('ix_password_reset_authorizations_reset_token_hash'), table_name='password_reset_authorizations')
    op.drop_index(op.f('ix_password_reset_authorizations_id'), table_name='password_reset_authorizations')
    op.drop_index(op.f('ix_password_reset_authorizations_email'), table_name='password_reset_authorizations')
    op.create_index(op.f('idx_pwd_reset_hash'), 'password_reset_authorizations', ['reset_token_hash'], unique=False)
    op.create_index(op.f('idx_pwd_reset_email'), 'password_reset_authorizations', ['email'], unique=False)
    op.alter_column('password_reset_authorizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_official_weekly_snapshots_session_id'), table_name='official_weekly_snapshots')
    op.drop_index(op.f('ix_official_weekly_snapshots_id'), table_name='official_weekly_snapshots')
    op.create_index(op.f('idx_official_weekly_snapshots_session_id'), 'official_weekly_snapshots', ['session_id'], unique=False)
    op.alter_column('official_weekly_snapshots', 'reconciliation_summary',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('official_weekly_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint('uq_official_public_session_student_version', 'official_public_participants', type_='unique')
    op.drop_index(op.f('ix_official_public_participants_is_active_version'), table_name='official_public_participants')
    op.drop_index(op.f('ix_official_public_participants_dataset_version'), table_name='official_public_participants')
    op.create_unique_constraint(op.f('uq_official_public_session_student'), 'official_public_participants', ['session_id', 'student_id'])
    op.add_column('notification_outbox_events', sa.Column('attempt', sa.INTEGER(), nullable=True))
    op.add_column('notification_outbox_events', sa.Column('next_run', sa.DATETIME(), nullable=True))
    op.add_column('notification_outbox_events', sa.Column('last_error', sa.TEXT(), nullable=True))
    op.add_column('notification_outbox_events', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_notification_outbox_events_status'), table_name='notification_outbox_events')
    op.drop_index(op.f('ix_notification_outbox_events_created_at'), table_name='notification_outbox_events')
    op.alter_column('notification_outbox_events', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index('ix_messages_unread_status', table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_index(op.f('ix_messages_client_message_id'), table_name='messages')
    op.drop_index(op.f('ix_leetcode_profile_stats_total_solved'), table_name='leetcode_profile_stats')
    op.drop_index(op.f('ix_leetcode_profile_stats_sync_status'), table_name='leetcode_profile_stats')
    op.create_index(op.f('idx_profile_stats_total_solved'), 'leetcode_profile_stats', ['total_solved'], unique=False)
    op.create_index(op.f('idx_profile_stats_sync_status'), 'leetcode_profile_stats', ['sync_status'], unique=False)
    op.create_index(op.f('idx_profile_stats_sync_solved'), 'leetcode_profile_stats', ['sync_status', 'total_solved'], unique=False)
    op.create_index(op.f('idx_profile_stats_student_id'), 'leetcode_profile_stats', ['student_id'], unique=False)
    op.create_index(op.f('idx_profile_stats_contest_rating'), 'leetcode_profile_stats', ['contest_rating'], unique=False)
    op.create_index(op.f('idx_lps_stud_solved_rating'), 'leetcode_profile_stats', ['student_id', 'total_solved', 'contest_rating'], unique=False)
    op.alter_column('leetcode_profile_stats', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('leetcode_profile_stats', 'sync_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'success'"))
    op.drop_index(op.f('ix_leetcode_accounts_id'), table_name='leetcode_accounts')
    op.create_index(op.f('idx_faculty_assign_stud'), 'faculty_student_assignments', ['student_id'], unique=False)
    op.create_index(op.f('idx_faculty_assign_fac_stud'), 'faculty_student_assignments', ['faculty_id', 'student_id'], unique=False)
    op.drop_constraint('uq_faculty_action_signal', 'faculty_action_queue', type_='unique')
    op.drop_index(op.f('ix_faculty_action_queue_signal_type'), table_name='faculty_action_queue')
    op.drop_index(op.f('ix_faculty_action_queue_created_at'), table_name='faculty_action_queue')
    op.drop_index(op.f('ix_faculty_action_queue_contest_id'), table_name='faculty_action_queue')
    op.alter_column('faculty_action_queue', 'escalated_to',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('faculty_action_queue', 'contest_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
    op.alter_column('faculty_action_queue', 'signal_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True,
               existing_server_default=sa.text("'ROUTINE_MONITORING'"))
    op.drop_index(op.f('ix_email_otp_records_request_ip_hash'), table_name='email_otp_records')
    op.create_index(op.f('idx_email_otp_request_id'), 'email_otp_records', ['request_id'], unique=False)
    op.create_index(op.f('idx_email_otp_email_hash'), 'email_otp_records', ['email_hash'], unique=False)
    op.create_index(op.f('idx_email_otp_created_at'), 'email_otp_records', ['created_at'], unique=False)
    op.drop_index(op.f('ix_contest_participations_source_username'), table_name='contest_participations')
    op.drop_index(op.f('ix_certificate_records_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_verification_id'), table_name='certificate_records')
    op.create_index(op.f('ix_certificate_records_verification_id'), 'certificate_records', ['verification_id'], unique=False)
    op.alter_column('certificate_records', 'document_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'CERTIFICATE_OF_EXCELLENCE'"))
    op.alter_column('certificate_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_authorized_signatures_id'), table_name='authorized_signatures')
    op.alter_column('authorized_signatures', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('idx_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_admin_audit_logs_event_timestamp'), table_name='admin_audit_logs')
    op.create_index(op.f('idx_audit_trace_id'), 'admin_audit_logs', ['trace_id'], unique=False)
    op.create_index(op.f('idx_audit_event_timestamp'), 'admin_audit_logs', ['event_timestamp'], unique=False)
    op.create_index(op.f('idx_audit_correlation_id'), 'admin_audit_logs', ['correlation_id'], unique=False)
    op.alter_column('admin_audit_logs', 'institution_logo_reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'assets/nec_logo.png'"))
    op.alter_column('admin_audit_logs', 'institution_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'NEC_AUTONOMOUS_001'"))
    op.alter_column('admin_audit_logs', 'previous_event_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'event_hash',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'denial_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admin_audit_logs', 'event_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
